name: Main CI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.1'

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-pub-cache-

      - name: Install dependencies
        run: flutter pub get

      - name: Cache build artifacts (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/cache@v2
        with:
          path: build/linux
          key: ${{ runner.os }}-flutter-linux-build-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-linux-build-

      - name: Cache build artifacts (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/cache@v2
        with:
          path: build/windows
          key: ${{ runner.os }}-flutter-windows-build-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-windows-build-

      - name: Cache build artifacts (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/cache@v2
        with:
          path: build/macos
          key: ${{ runner.os }}-flutter-macos-build-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-macos-build-

      - name: Analyze project (no fail)
        run: flutter analyze || true

      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: flutter build linux --release

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: flutter build windows --release

      - name: Build macOS
        if: matrix.os == 'macos-latest'
        run: flutter build macos --release

      - name: Strip macOS binary to reduce size
        if: matrix.os == 'macos-latest' && always()
        run: |
          FILE="build/macos/Build/Products/Release/*.app/Contents/MacOS/*"
          for f in $FILE; do
            if [ -f "$f" ]; then
              strip -x "$f"
            fi
          done

      - name: Upload Linux artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: linux-release
          path: build/linux/x64/release/

      - name: Upload Windows artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: build/windows/runner/Release

      - name: Upload macOS artifact
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-release
          path: build/macos/Build/Products/Release/*.app

      - name: Create GitHub Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: |
            🎉 Release of version ${{ github.ref_name }} for ${{ matrix.os }}.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/linux/x64/release/**/*
            build/windows/runner/Release/**/*
            build/macos/Build/Products/Release/**/*.app/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
